# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tubes1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from menu import *
import source_rc

class Ui_Masuk(object):
    def setupUi(self, Masuk):
        Masuk.setObjectName("Masuk")
        Masuk.resize(900, 600)
        Masuk.setStyleSheet("*{\n"
"    font-family:SF UI Text;\n"
"    font-size:24px;\n"
"    color:#3575FE;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:#333;\n"
"}\n"
"QPushButton\n"
"{\n"
"    background:#3575FE;\n"
"    border-radius:10px;\n"
"}\n"
"QToolButton\n"
"{\n"
"    background:#3575FE;\n"
"    border-radius:60px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#FFFFFF;\n"
"}")
        self.frame = QtWidgets.QFrame(Masuk)
        self.frame.setGeometry(QtCore.QRect(430, 0, 471, 601))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(130, 330, 211, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    color:#FFFFF;\n"
"    border-radius:10px;\n"
"    background:#7CA5FF;\n"
"}\n"
"*{\n"
"    font-size:18px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.MenuUtama)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 190, 241, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text;\n"
"    font-size:30px;\n"
"    color:#3575FE;\n"
"}")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(0)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text;\n"
"    font-size:30px;\n"
"    color:#3575FE;\n"
"}")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(-30, 0, 501, 51))
        self.frame_6.setStyleSheet("QFrame\n"
"{\n"
"    background:#FFFFFF;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_2 = QtWidgets.QFrame(Masuk)
        self.frame_2.setGeometry(QtCore.QRect(-40, 0, 481, 601))
        self.frame_2.setStyleSheet("QFrame\n"
"{\n"
"    background:#3575FE;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.toolButton_7 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_7.setGeometry(QtCore.QRect(100, 120, 301, 341))
        self.toolButton_7.setStyleSheet("QToolButton\n"
"{\n"
"    image: url(:/images/doctor1.png);\n"
"}")
        self.toolButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("QT/img/doctor1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon)
        self.toolButton_7.setIconSize(QtCore.QSize(400, 400))
        self.toolButton_7.setCheckable(False)
        self.toolButton_7.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_7.setAutoRaise(False)
        self.toolButton_7.setObjectName("toolButton_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(99, 0, 371, 51))
        self.frame_4.setStyleSheet("QFrame\n"
"{\n"
"    background:#FFFFFF;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.toolButton_4 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_4.setGeometry(QtCore.QRect(20, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("aharoni")
        font.setPointSize(-1)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setStyleSheet("*{\n"
"    font-family:aharoni;\n"
"    font-size:24px;\n"
"}\n"
"QToolButton\n"
"{\n"
"    background:transparent;\n"
"    border-radius:10px;\n"
"    color:white;\n"
"}\n"
"QToolButton\n"
"{\n"
"    color:#3575FE;\n"
"}")
        self.toolButton_4.setIconSize(QtCore.QSize(70, 70))
        self.toolButton_4.setCheckable(False)
        self.toolButton_4.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_4.setAutoRaise(False)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton = QtWidgets.QToolButton(self.frame_2)
        self.toolButton.setGeometry(QtCore.QRect(50, 10, 41, 31))
        self.toolButton.setStyleSheet("QToolButton\n"
"{\n"
"    \n"
"    image: url(:/images/logo.png);\n"
"    background:#3575FE;\n"
"    border-radius:60px;\n"
"}")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.frame_2.raise_()
        self.frame.raise_()

        self.retranslateUi(Masuk)
        QtCore.QMetaObject.connectSlotsByName(Masuk)

    def retranslateUi(self, Masuk):
        _translate = QtCore.QCoreApplication.translate
        Masuk.setWindowTitle(_translate("Masuk", "Dialog"))
        self.pushButton.setText(_translate("Masuk", "Masuk"))
        self.label.setText(_translate("Masuk", "Selamat Datang"))
        self.label_2.setText(_translate("Masuk", "di Health.i"))
        self.toolButton_4.setText(_translate("Masuk", "Health.i"))

    def MenuUtama(self):
        self.Form2 = QtWidgets.QDialog()
        self.ui = MenuUtama()
        self.ui.setupUi(self.Form2)
        self.Form2.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Masuk = QtWidgets.QDialog()
    ui = Ui_Masuk()
    ui.setupUi(Masuk)
    Masuk.show()
    sys.exit(app.exec_())
