# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tubes2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from registrasi import *
from obat import *
from bayar import *


class MenuUtama(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setStyleSheet("*{\n"
"    font-family:SF UI Text;\n"
"    font-size:20px;\n"
"    color:#3575FE;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:#F4F5F7;\n"
"}\n"
"QPushButton\n"
"{\n"
"    background:#FFFFFF;\n"
"    border-radius:10px;\n"
"}\n"
"QToolButton\n"
"{\n"
"    background:#3575FE;\n"
"    border-radius:60px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#3575FE;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 0, 841, 51))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    background:#FFFFFF;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("aharoni")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("*{\n"
"    font-family:aharoni;\n"
"    font-size:24px;\n"
"}")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.frame_3.setStyleSheet("QFrame\n"
"{\n"
"    background:#3575FE;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toolButton = QtWidgets.QToolButton(self.frame_3)
        self.toolButton.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.toolButton.setStyleSheet("QToolButton\n"
"{\n"
"    \n"
"    image: url(:/images/logo.png);\n"
"    background:#3575FE;\n"
"    border-radius:60px;\n"
"}")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 50, 900, 600))
        self.frame_4.setStyleSheet("QFrame\n"
"{\n"
"    background:#333;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(200, 120, 491, 351))
        self.frame_2.setStyleSheet("QFrame\n"
"{\n"
"    background:#3575FE;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 90, 211, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:hover\n"
"{\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background:#7CA5FF;\n"
"}\n"
"*{\n"
"    font-size:18px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.pageRegister)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 160, 211, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton:hover\n"
"{\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background:#7CA5FF;\n"
"}\n"
"*{\n"
"    font-size:18px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.pageObat)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 230, 211, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton:hover\n"
"{\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background:#7CA5FF;\n"
"}\n"
"*{\n"
"    font-size:18px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.pagePembayaran)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("\n"
"*{\n"
"    font-size:18px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    \n"
"    image: url(:/images/registrasi.png);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 160, 51, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("\n"
"*{\n"
"    font-size:18px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    \n"
"    image: url(:/images/obat.png);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 230, 51, 51))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("\n"
"*{\n"
"    font-size:18px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    \n"
"    image: url(:/images/pembayaran.png);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_4)
        self.toolButton_2.setGeometry(QtCore.QRect(380, 60, 121, 121))
        self.toolButton_2.setStyleSheet("QToolButton\n"
"{\n"
"    background:#FFFFFF;\n"
"    border-radius:60px;\n"
"}\n"
"*\n"
"{\n"
"    font-family:SF UI Text bold;\n"
"    font-size:29px;\n"
"    color:#3575FE;\n"
"}")
        self.toolButton_2.setObjectName("toolButton_2")
        self.frame_3.raise_()
        self.frame.raise_()
        self.frame_4.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Health.i"))
        self.pushButton_3.setText(_translate("MainWindow", "Registrasi Pasien"))
        self.pushButton_4.setText(_translate("MainWindow", "Ambil Obat"))
        self.pushButton_5.setText(_translate("MainWindow", "Bayar"))
        self.toolButton_2.setText(_translate("MainWindow", "Menu"))

    def pageRegister(self):
        self.Form2 = QtWidgets.QDialog()
        self.ui = Ui_Registrasi()
        self.ui.setupUi(self.Form2)
        self.Form2.show()

    def pageObat(self):
        self.Form3 = QtWidgets.QDialog()
        self.ui = ambilObat()
        self.ui.setupUi(self.Form3)
        self.Form3.show()

    def pagePembayaran(self):
        self.Form = QtWidgets.QDialog()
        self.ui = bayarObat()
        self.ui.setupUi(self.Form)
        self.Form.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MenuUtama()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
