# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tubes4.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QPushButton, QVBoxLayout, QLabel
import mysql.connector as mc



class windowSukses(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('Sukses')
        self.setFixedWidth(300)
        self.setStyleSheet("""
            
            QLabel{
                font-size: 20px
            }
            """)
        mainLayout = QVBoxLayout()
        self.ambil = ambilObat()
        
        self.nama = QLabel()
        self.ok = QPushButton('OK')
        mainLayout.addWidget(self.nama)
        mainLayout.addWidget(self.ok)
        self.nama.setText('Pengambilan Obat Di Proses')
        self.ok.clicked.connect(self.close)
        mainLayout.addWidget(self.ok)

        self.setLayout(mainLayout)

    def displayInfo(self):
        self.show()

class ambilObat(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 713)
        self.windowOke = windowSukses()
        Dialog.setStyleSheet("*{\n"
"    font-family:SF UI Text;\n"
"    font-size:20px;\n"
"    color:#3575FE;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:#F4F5F7;\n"
"}\n"
"QPushButton\n"
"{\n"
"    background:#FFFFFF;\n"
"    border-radius:10px;\n"
"}\n"
"QToolButton\n"
"{\n"
"    border-radius:60px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#3575FE;\n"
"}")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 901, 861))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    background:#333;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(60, 0, 841, 51))
        self.frame_2.setStyleSheet("QFrame\n"
"{\n"
"    background:#FFFFFF;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.label.setStyleSheet("*{\n"
"    font-family:aharoni;\n"
"    font-size:24px;\n"
"}")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.frame_3.setStyleSheet("QFrame\n"
"{\n"
"    background:#3575FE;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toolButton = QtWidgets.QToolButton(self.frame_3)
        self.toolButton.setGeometry(QtCore.QRect(10, 0, 41, 51))
        self.toolButton.setStyleSheet("QToolButton\n"
"{\n"
"    \n"
"    image: url(:/images/logo.png);\n"
"    border-radius:60px;\n"
"}")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(390, 110, 121, 121))
        self.toolButton_3.setStyleSheet("QToolButton\n"
"{\n"   
"    background:#FFFFFF;\n"
"    border-radius:60px;\n"
"}\n"
"*\n"
"{\n"
"    font-family:SF UI Text bold;\n"
"    font-size:29px;\n"
"    color:#3575FE;\n"
"}")
        self.toolButton_3.setObjectName("toolButton_3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(150, 180, 601, 351))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("QFrame\n"
"{\n"
"    background:#3575FE;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 91, 41))
        font = QtGui.QFont()
        font.setFamily("SF UI 57 12")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text Bold;\n"
"    font-size:16px;\n"
"    color:#FFFFFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(60, 140, 131, 41))
        font = QtGui.QFont()
        font.setFamily("SF UI 57 reguler")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text reguler;\n"
"    font-size:16px;\n"
"    color:#FFFFFF;\n"
"    background:transparent;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(60, 180, 180, 41))
        font = QtGui.QFont()
        font.setFamily("SF UI 57 reguler")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text reguler;\n"
"    font-size:16px;\n"
"    color:#FFFFFF;\n"
"    background:transparent;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(209, 230, 331, 22))
        self.lineEdit_2.setStyleSheet("*{\n"
"    font-family:SF UI Text;\n"
"    font-size:14px;\n"
"    color:#333;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(170, 60, 300, 41))
        font = QtGui.QFont()
        font.setFamily("SF UI 57 reguler")
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text reguler;\n"
"    font-size:18px;\n"
"    color:#FFFFFF;\n"
"    background:transparent;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(260, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SF UI 57 reguler")
        font.setPointSize(-1)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("*\n"
"{\n"
"    font-family:SF UI Text reguler;\n"
"    font-size:18px;\n"
"    color:#FFFFFF;\n"
"    background:transparent;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(210, 190, 331, 22))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("*{\n"
"    font-family:SF UI Text;\n"
"    font-size:14px;\n"
"    color:#333;\n"
"}")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setGeometry(QtCore.QRect(210, 150, 331, 22))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"    background:#FFFFFF;\n"
"}\n"
"\n"
"*{\n"
"    font-family:SF UI Text;\n"
"    font-size:14px;\n"
"    color:#333;\n"
"}")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 580, 211, 49))
        font = QtGui.QFont()
        font.setFamily("SF UI 57")
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:hover\n"
"{\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background:#7CA5FF;\n"
"}\n"
"*{\n"
"    font-size:18px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#FFFFFF;\n"
"    background:#3575FE;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.simpanData)
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.toolButton_3.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="rumah_sakit"

            )

            mycursor = mydb.cursor()
            query = "SELECT * FROM pasien"
            mycursor.execute(query)
            result = mycursor.fetchall()

        except mc.Error as e:
            print('gagal')
        for i in result:
            self.comboBox.addItem(str(i[1]))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Health.i"))
        self.toolButton_3.setText(_translate("Dialog", "Obat"))
        self.label_4.setText(_translate("Dialog", "Nama Obat"))
        self.label_2.setText(_translate("Dialog", "Nama Pasien"))
        self.label_3.setText(_translate("Dialog", "Diagnosa Sakit"))
        self.label_14.setText(_translate("Dialog", "Inputkan data obat dengan baik"))
        self.label_15.setText(_translate("Dialog", "dan benar"))
        self.pushButton_3.setText(_translate("Dialog", "Ambil Obat"))

    def simpanData(self):
        nama = self.comboBox.currentText()
        diagnosa = self.lineEdit_11.text()
        nama_obat = self.lineEdit_2.text()
        try:
                mydb = mc.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="rumah_sakit"

                    )

                mycursor = mydb.cursor()
                cekpasien = "SELECT * FROM pasien WHERE nama = %s"
                values = (nama,)
                mycursor.execute(cekpasien,values)
                result = mycursor.fetchall()
                for i in result:
                        id_pasiennya = i[0]
                
                query = "INSERT INTO pengambilan_obat (id_pasien,diagnosa,nama_obat,keterangan) VALUES (%s,%s,%s,%s)"
                value = (id_pasiennya,diagnosa,nama_obat,'Sudah Diambil')
                mycursor.execute(query,value)
                mydb.commit()
                print(nama,diagnosa,nama_obat)
                self.windowOke.displayInfo()

        except mc.Error as e:
                print('gagal')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ambilObat()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
